### ISSUE TITLE
Respect the Observable contract

### ISSUE THREAD

**Issue by pakoito** [ajalt/reprint#1]
Have a read and consider rewriting your wrapper, as it doesn't respect unsubscriptions, backpressure.

https://www.reddit.com/r/androiddev/comments/3u5w0c/if_you_are_writing_observablecreate_theres_a_big/

**Comment by ajalt** [comment]
You're right. `defer` and `fronCallable` don't work here, since `onNext` is called multiple times, but we do need to check for unsubscriptions. I'll thing about the best way to handle backpressure, but I'm open to suggestions on that.

**Comment by ajalt** [comment]
I added a backpressure strategy in 76f17d9, but feel free to suggest a more advanced solution if you have one.
