### ISSUE TITLE
reprint on sam sung android 5.0

### ISSUE THREAD

**Issue by phanvanduc** [ajalt/reprint#11]
reprint have on android under 6.0? thanks

**Comment by phanvanduc** [comment]
when i srun on samsung a5 then get error when  Reprint.authenticate(). Please help me.

**Comment by phanvanduc** [comment]
i get new error
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.ajalt.reprint.module.spass.R$string" on path: DexPathList
base.apk
lib/arm
/vendor/lib, /system/lib
thanks

**Comment by ajalt** [comment]
I'm not sure what you're asking. Please try provide more useful information.

http://stackoverflow.com/help/how-to-ask
http://stackoverflow.com/help/mcve
