### ISSUE TITLE
Potential for memory leaks.

### ISSUE THREAD

**Issue by Pear0** [ajalt/reprint#13]
For my app, I have LeakCanary set up and it found that an activity was leaked because a dialog I had created implemented the AuthenticationListener interface which was passed to Reprint.authenticate(). According to the [LeakCanary Dump](https://gist.github.com/Pear0/3407d3d7d599b3f8bf4264a5a5789861), Reprint looks to be holding onto the listener it's given which in my case kept the dialog and activity that launched it in memory. 

I have created a workaround for my app, but ideally Reprint would drop its references once authentication is complete.

If it matters, I'm running a Huawei Nexus 6P with Android 6.0.1.

**Comment by ajalt** [comment]
Hmm, interesting. Reprint doesn't keep a reference to the listener that you pass in. Looking at the dump, it it looks like it's actually `android.hardware.fingerprint.FingerprintManager` that's holding the reference. Right now Reprint keeps a global FingerprintManager to avoid reinitializing it on every call, but if the manager is leaking the listener, than I suppose that I could create a new manager on every reprint call as a workaround. I don't think that will solve the problem, though, since the FingerprintManager is a static system service.

What is the workaround that you use that works?

**Comment by Pear0** [comment]
It's not really a workaround so much as just mitigation. I have a static class that holds a weak reference to my dialog and forwards the calls so that the dialog and activity can still be garbage collected. It's not ideal, but it seems to work.

**Comment by ajalt** [comment]
Looking at it more, Reprint definitely doesn't hold any references to activity contexts. This leak would happen if you used the `FingerprintManager` directly, so there's nothing Reprint can do, unfortunately.

**Comment by Pear0** [comment]
I don't have the original code nor do I remember the exact situation but it boils down to this:

```java
/* 
 * SomeActivity is some heavyweight object that is very costly if leaked.
 */
public class SomeActivity extends Activity implements SomeListenerInterface {

    /*
     * MyListener is a minimal implementation of the necessary interfaces that forwards all of its 
     * method calls to the outer class if the parent has not been GC'd.
     *
     * Crucially, because this listener only holds a weak reference, it won't prevent SomeActivity from being GC'd. And because MyListener is a small object, it may still be leaked but it's a matter of bytes being leaked rather than megabytes if an Activity were leaked. 
     * 
     * This class must be static. A non-static inner class will hold a strong reference to the outer class which we can't have. 
     */
    static class MyListener implements SomeListenerInterface {
        private WeakReference<SomeActivity> ref;
        public MyListener(WeakReference<SomeActivity> ref) {
            this.ref = ref;
        }
        
        @Override
        public void someMethod(String arg) {
            // grab a temporary strong reference and check to make sure SomeActivity hasn't been GC'd.
            SomeActivity a = ref.get();
            if (a != null) {
                a.someMethod(arg);
            }
        }
    }

    @Override
    public void onCreate(Bundle savedState) {
        // instead of directly registering SomeActivity, register the custom listener.
        WhateverManager.addListener(new MyListener(new WeakReference(this)));
        ...
    }

    @Override
    public void someMethod(String arg) {
        // do whatever here
        System.out.println(arg);
    }
}
