### ISSUE TITLE
text issus when have support reprint but delete all reprint in device

### ISSUE THREAD

**Issue by phanvanduc** [ajalt/reprint#14]
when i delete all reprint in device, i get error "Too many attempts. Try again later."
Please change text other. Thanks

**Comment by ajalt** [comment]
I'm having trouble understanding what you're asking. What do you mean when you say you "delete all reprint in device"? Are you using a Samsung or a Nexus device?

**Comment by ajalt** [comment]
The text "Too many attempts. Try again later." is provided by Android on marshmallow, so reprint doesn't control it.
