### ISSUE TITLE
broken files when building release and proguard

### ISSUE THREAD

**Issue by MFlisar** [ajalt/reprint#17]
I'm getting following errors:

	:app:lintVitalRelease_pro
	Error processing ...\app\build\intermediates\exploded-aar\com.github.ajalt.reprint\reprint_spass\2.8.0\jars\libs\pass-v1.1.4.jar:com\samsung\android\sdk\pass\SpassFingerprint.class: broken class file?
	Error processing ...\app\build\intermediates\exploded-aar\com.github.ajalt.reprint\reprint_spass\2.8.0\jars\libs\pass-v1.1.4.jar:com\samsung\android\sdk\pass\support\SdkSupporter.class: broken class file?
	Error processing ...\app\build\intermediates\exploded-aar\com.github.ajalt.reprint\reprint_spass\2.8.0\jars\libs\pass-v1.1.4.jar:com\samsung\android\sdk\pass\support\v1\FingerprintManagerProxyFactory$a.class: broken class file?

Any ideas why this happens and how to solve that?

**Comment by ajalt** [comment]
That is strange, I've never seen that before. I include in the reprint aar the following proguard rules for the spass module:

```
-dontwarn com.samsung.**
-keep class com.samsung.** {*;}
```

If you are using the jar dependency, you wouldn't have those. I'd suggest making sure you are using the AARs in your gradle script. You could also try manually adding those proguard rules. Make sure you do a clean build.

**Comment by MFlisar** [comment]
I know those proguard rules, I suggested them ;-). 

I'm using the @aars and my own proguard file still has the proguard rules as well.

Since my last release build, I did following:

* updated support library 23.4.0 => 24.2.0
* updated build tools from 23.?.? => 24.0.0 (used the latest of v23)
* updates target sdk from 23 => 24
* updated gradle build tools from 2.1.2 => 2.1.3
* updated gradle from ? => 2.14.1 (used the latest that was common before)
* enabled instant run

I am not sure why it's not working anymore now. Maybe instant run or something with the newer gradle version? I tried a few things but could not find any work around yet. Any other ideas?

**Comment by ajalt** [comment]
You could rule out instant run and Android Studio by doing your project's equivalent to `./gradlew clean assembleRelease` from the command line.

**Comment by ajalt** [comment]
I just built a release build successfully using all the latest build tools, target sdk, and support libraries. I also see the warning about broken class files, but only from the lint task. Do the errors you're seeing prevent the app from building or working, or is it just that lint won't run on the spass jars?

**Comment by MFlisar** [comment]
My fault... I could build my project now, I oversaw one warning...

You're right, those `broken class file?` lines don't break the release build...

I've just never seen this lines before (I think, proguard problems occur every now and then and I'm looking through all lines then and never saw this error before)...

**Comment by ajalt** [comment]
I haven't seen those warning before either; I think they must have started showing up as a result of one of the newer libraries or build tools. Good to know that everything still works, though. Let me know if it causes any problems.
