### ISSUE TITLE
Not able to import in android studio

### ISSUE THREAD

**Issue by khyatiChitroda** [ajalt/reprint#18]
Hello, I have tried a lot to import this to android studio and eclipse also but I am getting this error,

> Error:Unable to load class 'org.gradle.internal.logging.LoggingManagerInternal'.
> Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> <a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> <a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
> 

Please help me,
Thank you in advance

**Comment by ajalt** [comment]
Have you tried following the advice in the error output? I've never had a problem opening this project in Android Studio, so I think the problem is on your end. Try deleting your gradle cache and restarting your computer.

**Comment by khyatiChitroda** [comment]
Yes, dear I have tried above solution but never work this.

**Comment by ajalt** [comment]
I'm sorry that I can't be more help, but since this isn't a problem with Reprint, I don't have any more advice.
