### ISSUE TITLE
Return some info for auth

### ISSUE THREAD

**Issue by g0ddest** [ajalt/reprint#19]
Is it possible to return some fingerprint hash or encrypt some value for external auth? `onSuccess` now return only `moduleTag`.

**Comment by ajalt** [comment]
The reason Reprint doesn't currently support crypto operations is that those operations would only be supported by the marshmallow module. The samsung pass sdk does not support signing or encryption at all. 

So I could potentially add that ability,  but it wouldn't be available on all the devices that authentication is available for.

**Comment by g0ddest** [comment]
Thank you. Samsung Pass SDK seems to be used only for internal auth.
