### ISSUE TITLE
Lib doesn't seem to work without retrolamda

### ISSUE THREAD

**Issue by joen93** [ajalt/reprint#22]
It seems that `retry(RxReprint.retryNonFatal(5))` doesn't work when not using retrolamda.
After the first (non-fatal) error, the fingerprint reader no longer seems to be listening for any input, and it no longer emits any errors nor codes.  

### How to reproduce
I changed [these lines in the sample app](https://github.com/ajalt/reprint/blob/master/sample/src/main/java/com/github/ajalt/reprint/MainActivity.java#L102) with the code below:
```java
RxReprint.authenticate()
                .doOnError(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        AuthenticationFailure e = (AuthenticationFailure) throwable;
                        showError(e.failureReason, e.fatal, e.errorMessage, e.errorCode);
                    }
                })
                .retry(RxReprint.retryNonFatal(5))
                .subscribe(new Subscriber<Integer>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onNext(Integer integer) {
                        showSuccess();
                    }
                });
```
Tried this on a nexus 6p (running android 7.1.1) and on an emulator with the 7.1.1. image.

However! Adding plenty of breakpoints seemed to solve the issue..

**Comment by ajalt** [comment]
Retrolambda is unrelated to this issue. What appears to be happening is that some change was made in Nougat that causes the fingerprint manager to silently fail when starting an auth request for some undocumented period of time after one was cancelled. `Reprint.authenticate` should still work fine.

I don't know of a way to fix this without changing the `RxReprint` api back to the 1.x version. I'm open to suggestions.

**Comment by bernardo-macedo** [comment]
@ajalt Is there any new development regarding this issue?

**Comment by ajalt** [comment]
@bernardo-macedo As far as I can tell, this is a bug in Nougat's fingerprint manager. The only way that I can find to work around this is to go back to an API like I had in Reprint 1.1, where the observable keeps emitting items until authentication succeeds or you're locked out. 

If you have any input on what you'd like to see in the API, let me know.

**Comment by ajalt** [comment]
@bernardo-macedo @joen93 : The newest release has an updated API that should work around the bug. Let me know if you still have problems, or if you have any feedback on the new API.
