### ISSUE TITLE
Null able logger in SpassReprintModule

### ISSUE THREAD

**Issue by mianharisali** [ajalt/reprint#23]
i think logger in SpassReprintModule should be null able.

**Comment by ajalt** [comment]
Reprint will never pass a null instance of a logger into a module. I designed it that way specifically so that modules don't have to do a null check every time they want to log something. Why do you think that should change?

**Comment by mianharisali** [comment]
https://github.com/ajalt/reprint/blob/master/reprint_spass/src/main/java/com/github/ajalt/reprint/module/spass/SpassReprintModule.java#L186

so this will not cause problem is logger is null?

**Comment by mianharisali** [comment]
sample code.
        Reprint.initialize(this);
        Reprint.registerModule(new SpassReprintModule(this,null));

**Comment by ajalt** [comment]
Yes, if you manually create an instance of the module and pass in null to a non-nullable parameter, it will cause an NPE. But `Reprint.initialize` will create and register the `SpassReprintModule` for you. There's no need to register in manually.

**Comment by mianharisali** [comment]
thanks for help :)
