### ISSUE TITLE
FingerPrint not working on samsung devices

### ISSUE THREAD

**Issue by natiq266** [ajalt/reprint#24]
this library sometimes works Randomly but mostly it's not working on samsung devices 
i have checked it on these android versions 5.1, 6.0, 7.0 on these samsung devices Galaxy S5 , S6, S7 Edge

i don't know what the issue exactly is but it should work all the time
i followed guide from the library same as its defined to integrate it

**Comment by ajalt** [comment]
The sample app works fine on Samsung devices, so there's probably an issue in how you're integrating the library. Have you tried the sample app on your devices? Make sure that you're including the right gradle dependencies in you integration, and that you're using the aar artifacts or including the right permissions in you manifest. Finally, make sure you're only initializing reprint once in your app, and not each tiem you start an activity.

**Comment by natiq266** [comment]
i have integrated same as you said In Application.onCreate, initialize Reprint with Reprint.initialize(this) once
then in my LockService's onCreate i called 

Reprint.authenticate(new AuthenticationListener() {
    public void onSuccess(int moduleTag) {
        showSuccess();
    }
    public void onFailure(AuthenticationFailureReason failureReason, boolean fatal,
                          CharSequence errorMessage, int moduleTag, int errorCode) {
        showError(failureReason, fatal, errorMessage, errorCode);
    }
});


added this in my build.gradle within android{ }

repositories {
    maven { url "https://jitpack.io" }
}

added all these dependencies in same gradle (app:gradle)
 compile 'com.github.ajalt.reprint:core:3.1.0@aar' // required: supports marshmallow devices
   compile 'com.github.ajalt.reprint:reprint_spass:3.1.0@aar' // optional: support for pre-marshmallow    compile 'com.github.ajalt.reprint:rxjava:3.1.0@aar' // optional: the RxJava 1 interface
   compile 'com.github.ajalt.reprint:rxjava2:3.1.0@aar' // optional: the RxJava 2 interface

and added those permissions in manifes


<uses-permission android:name="android.permission.USE_FINGERPRINT"/>


<uses-permission android:name="com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY"/>

**Comment by natiq266** [comment]
also tried your sample apk 
https://github.com/ajalt/reprint/releases/download/2.5.6/sample-debug.apk
its showing only that fingerprint is present,registered and listening but onSuccess() never called

**Comment by ajalt** [comment]
You said you were trying to run this from a service? That's probably the issue. Many versions of android won't let you use the fingerprint sensor unless you have a foreground activity.

**Comment by natiq266** [comment]
yes i think this was the issue before...
but now i am inflating view by adding it to window manager within service but i am starting service like this to bring it to front/foreground by intent flags

 Intent i = new Intent(context, LockService.class);
        i.setAction(ACTION_LOCK_SCREEN);
        i.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_CLEAR_TASK
                | Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_RECEIVER_FOREGROUND
                | Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
                | Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        context.startService(i);

now my view is on the top of all view but its still not working....even on that view fingerprint sensor not listening neither correct finger nor wrong finger

**Comment by ajalt** [comment]
A foreground service is not enough. You need a foreground *activity*.
