### ISSUE TITLE
Working only after resuming from standby

### ISSUE THREAD

**Issue by manuelpaulo** [ajalt/reprint#25]
Turning phone off and on, and using the fingerprint, first to unlock the phone and then to unlock my app works fine.

Using it again fails every time. AuthenticationListener for the Reprint.authenticate seems like it is not listening. No messages.

Thanks for any clue.

**Comment by ajalt** [comment]
Does this problem happen with the demo app, or your own? What phone are you using? What version of android?

**Comment by manuelpaulo** [comment]
My own. iPhone 6 Plus. Android 6.

**Comment by ajalt** [comment]
> iPhone 6 Plus

What? This is an android library, it doesn't work on iPhones. What device are you using to test this library with?

Try running the sample app. If it works, then the problem is with your code, not Reprint.

**Comment by manuelpaulo** [comment]
I am very sorry about the iPhone 6, I do apps for both iOS and Android and I have two main phones and made a mistake when replaying. I main Android phone does not have fingerprint, I test the fingerprint on the emulator. Thanks.

**Comment by ajalt** [comment]
Can you give me a stripped down example of how you're using the library? I've never heard of anyone else having this problem. Try taking a look at how the sample works to make sure you understand what you're doing.

**Comment by manuelpaulo** [comment]
I do Reprint.initialize and Reprint.authenticate on create and on resume. The thing is, I get onSuccess only when coming out of the standby. Can it be an emulator issue? 

I am going to test your demo code now and post the result here.

**Comment by manuelpaulo** [comment]
Tested. Your code works real fine. :(

**Comment by ajalt** [comment]
`Reprint.initialize` should only be called once in your app's `onCreate` method, not every time your activity starts.

**Comment by manuelpaulo** [comment]
Thanks. I have fixed it. It was indeed the double Reprint.initialize call. Now I only do Reprint.initialize and Reprint.authenticate on resume and it works.
