### ISSUE TITLE
Restart fingerprint authentication onsuccess

### ISSUE THREAD

**Issue by PG90** [ajalt/reprint#27]
onSuccess the scanner doesn't work in background android service. Just works one time before onSuccess happens. How to restart the process in service?

**Comment by ajalt** [comment]
You can't use the fingerprint sensor in a service on newer android models. You need to have a foreground activity. Unfortunately, there's no way around that.

**Comment by PG90** [comment]
It works fine for one time, but how to restart onTraditional method again automatically in background service ?

**Comment by PG90** [comment]
is there any method to start authenticating again onSuccess in this library?

**Comment by ajalt** [comment]
Like I said, unless you have a foreground activity, the authentication may not work. That's a limitation of the android system, not this library.

**Comment by PG90** [comment]
But as you can see many apps uses fingerprint unlock system for Applock in their background services without any forground activity, so I asked.

You can check this App-
https://play.google.com/store/apps/details?id=com.domobile.applock

This allows user to use fingerprint unlock in background service for applock, so there might be some way  
for this problem. Let me know if you can help.

**Comment by ajalt** [comment]
That app starts an activity which then starts the fingerprint authentication.

**Comment by PG90** [comment]
Ok Thanks
