### ISSUE TITLE
Proguard - missing rules

### ISSUE THREAD

**Issue by MFlisar** [ajalt/reprint#3]
Following rules work but may be able to be improved:

    -dontwarn com.samsung.**
    -keep class com.samsung.** {*;}

You should add a proguard file to the project..

**Comment by ajalt** [comment]
Fixed in 8aa2189. Thanks!

**Comment by MFlisar** [comment]
Perfect :-)

Btw, really nice library that's working fine

**Comment by ajalt** [comment]
Glad you like it! If you don't mind me asking, what app are you including this library in? I'm curious how people are using it.

**Comment by MFlisar** [comment]
Here you go: https://plus.google.com/u/2/communities/107213953584663540470

I use it in a gallery app...
