### ISSUE TITLE
Create a method that detects fingerprint changes

### ISSUE THREAD

**Issue by peterbetos** [ajalt/reprint#30]
Can you expose a method that handles KeyPermanentlyInvalidatedException and return a boolean once the library detects a fingerprint change?

**Comment by ajalt** [comment]
That's probably possible. Can you give me an example of what you'd want the usage to look like?

**Comment by peterbetos** [comment]
```
if (Reprint.hasFingerprintChanged()) {
    showFingerPrintChangesAlert();
}
```

**Comment by hatpick** [comment]
Use case:
In an app that can be unlocked both with user's password and fingerprints, if fingerprint has changed ask for user's password.

**Comment by ajalt** [comment]
The use case makes sense, but Reprint doesn't use a crypto object when authenticating. It would have to create and store a key in order to check for invalidation, which I don't think is desirable.

**Comment by Morteza-Rastgoo** [comment]
This is something needed.
