### ISSUE TITLE
Samsung module

### ISSUE THREAD

**Issue by ChriCon** [ajalt/reprint#32]
How can I add SpassReprintModule for Samsung?
thank you

**Comment by ajalt** [comment]
As long as you include the module dependency (`com.github.ajalt.reprint:reprint_spass:3.2.1@aar`), the module is loaded automatically when you initialize reprint. You don't need to do anything extra.

**Comment by ChriCon** [comment]
I added this dependencies:
 compile 'com.github.ajalt.reprint:core:3.2.1@aar'
   compile 'com.github.ajalt.reprint:reprint_spass:3.2.1@aar' 
   compile 'com.github.ajalt.reprint:rxjava:3.2.1@aar' 
   compile 'com.github.ajalt.reprint:rxjava2:3.2.1@aar'
but I get this error:
Failed to resolve: com.github.ajalt.reprint:core:3.2.1
