### ISSUE TITLE
spass startIdentify or startIdentifyWithDialog

### ISSUE THREAD

**Issue by kokchyuan** [ajalt/reprint#33]
try to integrate this aar to my proj but i notice the dialogue is not appear for samsung pass devices, after dig into your codes and found out you are using startIdentify instead of startIdentifyWithDialog, any reason of this?

**Comment by ajalt** [comment]
Yes. This library is focused on providing a easy authentication flow, but the UI is up to you. Android Imprint doesn't have the equivalent to `startIdentifyWithDialog`: it's Samsung only. If you want that behavior, you can call it yourself.
