### ISSUE TITLE
Use with Gradle 3 "implementation" (instead of compile)

### ISSUE THREAD

**Issue by hatpick** [ajalt/reprint#37]
Hello,

I don't know if it's jitpack or reprint but I can't use the library with gradle 3:
```implementation 'com.github.ajalt.reprint:core:3.2.1@aar'```

Any help is appreciated

**Comment by ajalt** [comment]
* What version of gradle are you using? 
* What is the error you see with `implementation` that you don't with `compile`?
* Are you using any reprint modules other than `core`?

**Comment by hatpick** [comment]
I'm using gradle 3.1.3, trying to use both core and samsung-spass. it says that it can't find it.

**Comment by ajalt** [comment]
Hm, that gradle version is pretty old. Try upgrading to 4.4.1, or 4.8.1 (you'll need to disable configure on demand in your Android Studio settings for the latter)

**Comment by hatpick** [comment]
Sorry I put the ```com.android.tools.build:gradle:3.1.2``` version, I'm using 4.4

**Comment by hatpick** [comment]
Update: I tried it again today and it seems like it was jitpack issue, it's working now.
