### ISSUE TITLE
its not working in service but in activity its working fine 

### ISSUE THREAD

**Issue by Mateeen** [ajalt/reprint#38]

**Comment by ajalt** [comment]
You can only initiate an authentication request from a foreground service. This is a limitation enforced by Android. Let me know if you encounter a bug with Reprint itself, but I don't think there's anything we can do.

**Comment by Mateeen** [comment]
Its wroking in simple service but when screen become off or locked its not
work there in running servicw

**Comment by ajalt** [comment]
Maye you're running into the same problem as  #25? Are you calling `Reprint.initialize` in you service?

**Comment by hung1994v** [comment]
its working fine in service for some device , but on xiaomi red mi 3 it not working, when i open application and run service authentication can detect fingerprint
