### ISSUE TITLE
BiometricPRompt support and Spass version 1.2.6

### ISSUE THREAD

**Issue by kenshin171** [ajalt/reprint#40]
Hi, great library. 2 Questions.

1) Is there any intention to support the new upcoming  BiometricPrompt api from google?
2) Does the new version of Spass, version 1.2.6 resolve https://github.com/ajalt/reprint/issues/6?

**Comment by ajalt** [comment]
1. It's not out of the question. What would you like to see in terms of an api?
2. Unfortunately no, although Reprint now only uses the Spass module on KitKat devices, so the impact of the bug is reduced. If support for the small number of Samsung devices with fingerprint readers running KitKat is not a high priority, you can remove the `reprint_spass` module, and all newer devices should continue to work.

**Comment by kenshin171** [comment]
1) In terms of API, should be the same with a little more generic support of all biometrics which i guess Google is planning for the future where multiple forms of biometric authentication is possible e.g. face, voice? in addition to fingerprint. Maybe an enum to select which form of biometric to use? But this maybe in the future as even biometricprompt api does not support anything more than fingerprint at the moment. Another point is the fingerprintManager is marked for deprecation in api 28 onwards, so biometricPrompt api is the way to go as it is also a compat library https://mvnrepository.com/artifact/androidx.biometric/biometric

2) Unfortunately for my project i need to continue support for phones with fingerprint sensors that only support spass e.g. Samsung Galaxy s5 and note 4. So can i still use the Spass module even with version Reprint 3.3.0?

**Comment by ajalt** [comment]
Yes, you can continue to use Reprint 3.3.0, but you may run into the mentioned issue. If you don't need androidx support, you may want to remain on the previous version.

**Comment by kenshin171** [comment]
> Yes, you can continue to use Reprint 3.3.0, but you may run into the mentioned issue. If you don't need androidx support, you may want to remain on the previous version.

by Issue do u mean https://github.com/ajalt/reprint/issues/6 ? I thought the sPass Module uses spass sdk version 1.1.4 to avoid https://github.com/ajalt/reprint/issues/6? or did i misunderstand something

**Comment by ajalt** [comment]
You are correct, but Spass 1.1.4 doesn't work with androidx. Reprint 3.3.0 converted to androidx, so it has to use the latest Spass version, which contains the bug.

**Comment by kenshin171** [comment]
juz a random thought, to avoid the infamous https://github.com/ajalt/reprint/issues/6. Would it be able to just continue to use 1.1.4 version fo spass sdk but jetifiy it for androidX support? https://developer.android.com/studio/command-line/jetifier states that it support jar files.

e.g.
`jetifier-standalone -i pass-v1.1.4.jar -o pass-v1.1.4-jetified.jar`

**Comment by ajalt** [comment]
That's a good idea, but unfortunately it fails as discussed [here](https://github.com/ajalt/reprint/pull/39#issuecomment-427665870).

**Comment by ajalt** [comment]
Ok, I added a check to make sure that the marshmallow module works and falls back to spass if possible. Can you try the snapshot build and let me know if it works? You can just change your reprint version number to `-SNAPSHOT`. e.g. `compile 'com.github.ajalt.reprint:core:-SNAPSHOT@aar'`

**Comment by kenshin171** [comment]
Unfortunately the `-SNAPSHOT` is not working, i am getting `Fingerprint hardware not available`

**Comment by ajalt** [comment]
Ok, I update the logic in 21c69de, give the snapshot a try again.

**Comment by kenshin171** [comment]
@ajalt Awesome! 

I tested on both Spass phone and a fingerPrintManager phone. Both works as expected.

- [x] Spass - Samsung Galaxy S5 (android 6)
- [x] FingerprintManager - Google Pixel 2 XL (android 9)

**Comment by ajalt** [comment]
Thanks for testing! I released version 3.3.1 with the fix, let me know if you find any more issues.
