### ISSUE TITLE
Failed to transform file 'reprint_spass-3.2.1.aar'

### ISSUE THREAD

**Issue by mianaliasjad** [ajalt/reprint#42]
i have migrated my project to android x  
but while compiling "implementation 'com.github.ajalt.reprint:reprint_spass:3.2.1@aar'"
but core dependency working fine 
i am getting this error  

Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'reprint_spass-3.2.1.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform

**Comment by ajalt** [comment]
Please upgrade to the latest reprint version, 3.3.1, and let me know if you still have issues.
