### ISSUE TITLE
Also Use USE_BIOMETRIC Permission

### ISSUE THREAD

**Issue by peterbetos** [ajalt/reprint#43]
Can you transform the library to **also** utilize **androidx.biometric:biometric**?

**Comment by ajalt** [comment]
I'm not clear on your request. Can you provide more details on what you want?

**Comment by peterbetos** [comment]
I meant USE_FINGERPRINT permission was already deprecated starting on Android Pie. Can we also have the library USE_BIOMETRIC as well for Android Pie compatibility?

**Comment by kenshin171** [comment]
Technically, reprint 3.3.1 can also be used on android Pie, the question should be to swap out `FingerprintCompatManager` api to `BiometricPrompt` api from the androidx BiometricPrompt library from Google. This library should provide support for android devices which utilises any form of biometric authentication **not only fingerprint**.

However it is currently in alpha, alpha-03 to be exact, as shown here https://developer.android.com/jetpack/androidx/releases/biometrics#1.0.0-alpha03 and here in maven https://mvnrepository.com/artifact/androidx.biometric/biometric/.

Perhaps a branch in preparation for use of this new biometricprompt library?

This library also is aa appCompat library as it supports api level 14 onwards.

**Comment by ajalt** [comment]
This library doesn't use `FingerprintManagerCompat` any more, due to bugs in it's implementation. So I probably won't use the androidx library either. I don't see a reason not to add the `USE_BIOMETRIC` in addition to `USE_FINGERPRINT`, however.

**Comment by kenshin171** [comment]
Ah my apologies I meant `FingerprintManager` not `FingerprintManagerCompat`. As stated in https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager it's deprecated in API 28 in favour of androidx `biometricPrompt` api

**Comment by benwicks** [comment]
I started a PR with this change but I closed it because it would require devices with Pie to use a hacky workaround to determine if a fingerprint is registered. This may cause even more compatibility issues. I'll keep the branch around if anyone wants to look into it more.

**Comment by ajalt** [comment]
Echoing @benwicks comment, it looks like using `BiometricPrompt` has no advantages currently (since it just forwards calls to  `FingerprintManager`), and does have some drawbacks (the workaround). So I'm going to keep using `FingerprintManager` for now, but we can revisit this when future versions of Android come out.

Thanks again to @benwicks for working on this!
