### ISSUE TITLE
Face authentication

### ISSUE THREAD

**Issue by sahargal** [ajalt/reprint#45]
hi i am trying to find if in this library exits too face auth and finger print?
as i can see now there is only finger print

**Comment by ajalt** [comment]
Only fingerprint. I don't know of any current APIs to allow broader biometric authentication, although I'll look into supporting them if any show up.

**Comment by saharvx9** [comment]
Thanx man for the assistance(same yser that asked lol)
As i read for android pie exits FACE_FEATURE on the documantion:
https://developer.android.com/about/versions/pie/android-9.0
but there is not any existance at any other docs or on the api itself

**Comment by ajalt** [comment]
Some phones certainly have face unlock, but AFAIK, there are no public SDKs allowing access to them. The Android P BiometricPrompt that they added [only supports fingerprints](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/biometrics/BiometricPrompt.java) right now. I imagine it will expand its capabilities in the future.

**Comment by edgar-zigis** [comment]
@ajalt I just would like to thank you for this great library. This is much more stable than androidx BiometricPrompt :)

**Comment by hatpick** [comment]
@ajalt any updates on this? I think it's now supported with Android 10:
https://source.android.com/security/biometric/
Includes fingerprint and face authentication integration for [BiometricPrompt](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/biometrics)

**Comment by ajalt** [comment]
@hatpick  `BiometricPrompt` does indeed support face and iris authentication in Android 10. Its interface is fundamentally different than Reprint and the various fingerprint auth APIs, in that it mandates the use of a system-provided dialog. AFAICT, there's no way to support face and iris unlock with the current Reprint API.

The Samsung SPASS library has been deprecated for years now, and I don't believe it's even available for download on their website any more. Samsung is using `BiometricPrompt` for their face unlock going forward, so there isn't a separate Samsung-specific library for it.

So I can see a few ways forward for this library:

1. Leave it as-is. Let people continue to use it to implement their own UI for fingerprint auth, and use `BiometricPrompt` for other use cases.
2. Deprecate the library, and encourage people to use `BiometricPromptCompat` instead.
3. Rewrite the library to just provide extensions to BiometricPromptCompat that work with RxJava/Kotlin coroutines etc. It would no longer integrate Samsung SPASS, and would not support authentication without a system dialog.

I'd like to hear people's thoughts.

**Comment by edgar-zigis** [comment]
@ajalt indeed not the second option. BiometricPrompt system dialog just looks lame, why not letting people to change UI themselves? I hope though there will be a reliable Face Api detection in the future.

**Comment by ajalt** [comment]
The rationale behind requiring a system prompt is to make it consistent across apps so that users feel more confident in authenticating. Making the system dialog mandatory makes it impossible for apps to authenticate silently without the user knowing. 

I don't expect that there will ever be a way to do face unlock without a system dialog.

**Comment by edgar-zigis** [comment]
Yeah, and their dialog is ugly for older apis lower than 28.
