### ISSUE TITLE
Listeners should be set to null after calling onFailure or onSuccess to avoid memory leak

### ISSUE THREAD

**Issue by yeltayev22** [ajalt/reprint#46]
https://github.com/ajalt/reprint/blob/7eec3af2e9eac28ec9e0f567d61bd51f66db51cc/core/src/main/java/com/github/ajalt/reprint/module/marshmallow/MarshmallowReprintModule.java#L252

**Comment by ajalt** [comment]
Do you have evidence that this is actually a leak? It was my understanding that the entire `AuthenticationCallback`  object is freed after it's called once.

**Comment by yeltayev22** [comment]
My app detected leak through Leak canary and after setting those listeners to null, leak disappeared. I think the same as #13.

**Comment by ajalt** [comment]
Thanks for the report. I released version 3.3.2, which contains this change. Let me know if it fixes the problem.
