### ISSUE TITLE
onFailure immediately called on some devices

### ISSUE THREAD

**Issue by yeltayev22** [ajalt/reprint#47]
I read issue #4, however it gets called immediately onFailure only on some devices (in my case Meizu)? onFailure gets called with AuthenticationFailureReason `SENSOR_FAILED` with error code `1001`. Is it possible to handle such cases?

**Comment by yeltayev22** [comment]
Android 7.0, API 24

**Comment by ajalt** [comment]
If the device is reporting sensor failed, then I'm not sure there's anything we can do.

**Comment by tackanoway35** [comment]
I have same issue on Redmi 6 pro. onFailure immediately called when i call Reprint.authenticate Although I haven't verified the fingerprint yet
