### ISSUE TITLE
Reprint.initialize() is blocking, if fingerprint sensor has problems

### ISSUE THREAD

**Issue by MFlisar** [ajalt/reprint#7]
I get following log messages when calling `Reprint.initialize(MainApp.this);` in my app class:

```
FingerprintManager: ensureServiceConnected: mService is null
FingerprintManager: waitForService: called
FingerprintManager: waitForService: Timeout
```

And whenever I want to start the fingerprint reader I get this exception as well... Any ideas why this is happening?

It's probably some software problem, because it worked before on my phone and all I changed is, that I installed a custom recovery on my phone (a Samsung Galaxy Alpha).

Still, this results in two common problem: 
- `Reprint.initialize(MainApp.this);` is blocking the app start extremely
- any usage of `Reprint` is blocking again

_Suggestions_:
-  `Reprint.initialize(MainApp.this);` should be run asnychronously and any use of the `Reprint` API should block until the init function is finished
- if  `Reprint.initialize(MainApp.this);` fails, further calls to use Reprint should fail instantly instead of always checking the fingerprint hardware again

**Comment by ajalt** [comment]
Does this happen on any sanctioned ROM, or only homebrew stuff?  Asynchronous initialization has enough potential problems that I'd like to avoid it if only custom ROMs are affected.

**Comment by MFlisar** [comment]
In my case it's just a custom recovery with the stock rom and the problem was temporary, after a restart it worked again.

Still, this problem may occur with a custom rom and with partially broken hardware as well... Fingerprint sensor is no necessary hardware part for most people, having a defect one will though affect apps using this library heavily...

Don't know how often things like that occur though..

**Comment by ajalt** [comment]
I'm closing this for now, but let me know if this ever occurs in a stock ROM.
