### ISSUE TITLE
Reprint.cancelAuthentication() Not Working in Service

### ISSUE THREAD

**Issue by saeed74** [ajalt/reprint#9]
Reprint working perfect on Activitys.
But in Service when new AuthenticationListener starts, it work only in first time that service started and when that service killed and start again, AuthenticationListener  not working, untill app re install or clear data happen.
 in my Service onDestroy:

```
public void onDestroy() {
        super.onDestroy();
        Reprint.cancelAuthentication();
}
```

I think problem is becouse of Reprint.cancelAuthentication(); not working in service.
I test it by calling Reprint.cancelAuthentication(); inside of onFailure callback and it stop listener on first  onFailure in activity but not in service.

**Comment by saeed74** [comment]
ok i think this issue is related to this android os bug:
https://code.google.com/p/android/issues/detail?id=198151

**Comment by ajalt** [comment]
Yes, there's nothing we can do about that. That's not a bug in reprint, it's a bug in Nexus Imprint. The Samsung Pass reprint module works fine from a service.
